-- MIGRATION 006: ADD OWNER SIGNATURE AND DESCRIPTION COLUMNS
ALTER TABLE settings ADD COLUMN IF NOT EXISTS owner_signature_label VARCHAR(255);
ALTER TABLE settings ADD COLUMN IF NOT EXISTS owner_signature_description VARCHAR(255);
ALTER TABLE settings ADD COLUMN IF NOT EXISTS signature_1_description VARCHAR(255);
ALTER TABLE settings ADD COLUMN IF NOT EXISTS signature_2_description VARCHAR(255);
ALTER TABLE settings ADD COLUMN IF NOT EXISTS signature_3_description VARCHAR(255);
ALTER TABLE settings ADD COLUMN IF NOT EXISTS signature_4_description VARCHAR(255);
