-- MIGRATION 007: ADD MARKETING PAGES COLUMNS
ALTER TABLE settings ADD COLUMN IF NOT EXISTS marketing_pages TEXT DEFAULT '[]';
ALTER TABLE reports ADD COLUMN IF NOT EXISTS attach_marketing_pages BOOLEAN DEFAULT FALSE;
